# rabbitmq
spring:
  # 开启aop
  aop:
    auto: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    cache:
      channel:
        size: 2048
    listener:
      simple:
        prefetch: 10
  # 设置缓存工具以及配置信息
  cache:
    type: redis
    caffeine:
      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=60s
  # zipkin配置
  zipkin:
    rabbitmq:
      queue: zipkin
    locator:
      discovery:
        enabled: true
    sleuth:
      sampler:
        probability: 1.0F
      baggage-keys:
        - record_info
        - request_ip
# actuor服务监控暴露端口
management:
#  health:
#    redis:
#      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
#    shutdown:
#      enabled: true
# 熔断配置
hystrix:
  threadpool:
    default:
      coreSize: 20
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 180000
ribbon:
  #  ribbon请求连接的超时时间
  ConnectTimeout: 300
  #  请求处理的超时时间
  ReadTimeout: 200000
  OkToRetryOnAllOperations: true
  # 当前实例全部失败后可更换实例次数
  MaxAutoRetriesNextServer: 1
  # 当前实例只重试次数
  MaxAutoRetries: 0
  #  (MaxAutoRetries+1)*(MaxAutoRetriesNextServer+1) * (feign[maxAttempts])= 最终重试次数
  # 使用OKhttpFeignClient
  okhttp:
    enabled: true
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  hystrix:
    enabled: true