# rabbitmq
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  redis:
    database: 10
    lettuce:
      pool:
        max-active: 30
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
    timeout: 2000ms
    host: 49.233.31.66
    port: 6379
    password:
  cache:
    type: redis
    caffeine:
      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=60s
security:
  jwt:
    key: yun
    #毫秒 -- 30分钟
    timeOut: 1800000
