spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yi-yun?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    连接池指定 springboot2.02版本默认使用HikariCP 此处要替换成Druid
    druid:
#      初始化大小，最小，最大
      initial-size: 10
      min-idle: 10
      maxActive: 20
#      配置获取连接等待超时的时间
      maxWait: 60000
#      配置一个连接在池中最小生存的时间，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 'X'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
#      是否缓存preparedStatement，也就是PSCache MySQL下建议关闭
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
#      配置监控统计拦截的filters，去掉后监控界面sql无法统计，’wall’用于防火墙
      filters: stat,wall,log4j
#      通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
#      WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
#      是否启用StatFilter默认值true
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/druid/*"
        allow:
        reset-enable: false
        login-username: admin
        login-password: 123456
        enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
