spring:
  security:
    oauth2:
      jwt:
        signingKey: yun
        #毫秒 -- 30分钟
        timeOut: 1800000
    basic:
      enabled: true
      path: /swagger-ui.html
    user:
      name: admin
      password: admin