spring:
  redis:
    database: 10
    lettuce:
      pool:
        max-active: 30
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
    timeout: 2000ms
    host: 127.0.0.1
    port: 6379
    password: